.TH "StbResize" 1 1.8 "17 Jan 2023" "User Manual"

.SH NAME
stbresize

.SH DESCRIPTION
The image is scaled using interpolation:
  - bicubic (4x4)
  - biakima (6x6) 
  - biline (2x2)

The image is resampled using:
  - gsample (3x3)

Include prefilter:
  - Gauss (for downsample)
  - "Reverse Interpolate Scale (RIS)"

.SH SYNOPSIS
stbresize [options] image_in out.png

.SH OPTIONS
.TP
-H NUM
resize height (default 0)
.TP
-W NUM
resize width (default 0)
.TP
-i
use RIS prescale (default 0)
.TP
-m NUM
method: 0 - bicubic, 1 - biakima, -1 - biline, -2 - gsample (default 0)
.TP
-p N.N
part prefilter RIS (default 0.0)
.TP
-r N.N
sample ratio (default 1.0)
.TP
-h
show this help message and exit

.SH EXAMPLE
stbresize -r 2 data.png data.out.png 
 
 Load: data.png
 image: 1873x1000:3
 resize: 3746x2000:3
 method: bicubic
 Save png: data.out.png

.SH COPYRIGHT
This is free and unencumbered software released into the public domain.

.SH SEE ALSO
convert(1), gm(1), imagew(1)

.SH CONTACTS
Website: https://github.com/ImageProcessing-ElectronicPublications/stb-image-resize
