#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION
#define BIAKIMA_IMPLEMENTATION
#define BICUBIC_IMPLEMENTATION
#define BILINE_IMPLEMENTATION
#define GSAMPLE_IMPLEMENTATION
#define RIS_IMPLEMENTATION
#define HRIS_IMPLEMENTATION
#define GAUSS_IMPLEMENTATION
#include <stb/stb_image.h>
#include <stb/stb_image_write.h>
#include "biakima.h"
#include "bicubic.h"
#include "biline.h"
#include "gsample.h"
#include "ris.h"
#include "hris.h"
#include "gauss.h"
